### PR TITLE
Look for .api file in a case-insensitive manner

### LINKED ISSUE #76: Top-level projects don't seem to work on all OS's
I'm not entirely sure if I'm reading this all right, but in our single-project repo doesn't appear to work when running `apiCheck` on linux CI while it does work on macOS locally.

Here's a repro - https://github.com/slackhq/EitherNet/pull/52. Fails on CI with a strange check that suggests it's expecting a subproject, but it's a single-project repo only.

### PR DESCRIPTION
**Pull request by qwwdfsad**
Fixes #76

### CODE REVIEW

**Comment by ilya-g** [comment]
Maybe it's worth to log a warning when the case of an api file name doesn't match the expected case?
Could `apiDump` task be changed to normalize the case of the file name?

**Review by ilya-g — APPROVED** [review]

**Comment by qwwdfsad** [comment]
Sorry, thought we've discussed it on meeting, should've written the rationale anyway.

The problem with mixed case sensitive/case-insensitive is that there is no single source of truth -- if the project is being developed exclusively on OS X, than CamelProjectCase can be preferable over normalized file name. Normalizing it will also trigger disruptive change for everyone updated, which isn't a good thing.

Also, the original issue (https://github.com/slackhq/EitherNet/pull/52) is really weird and it's hard to tell whether a single change in minor Gradle version leading to changing the case of project name in the Gradle model a desired behaviour or a bug and triggering a warning over such thing doesn't seem reasonable to me.

**Comment by ZacSweers** [comment]
unfortunately it looks like it still fails in 0.9.0 :/. Same PR

**Comment by ZacSweers** [comment]
part of the problem is that it uses the project name (which has capital letters). If I regenerate it with all lowercase, then it works. It does seem to expect it to be all lowercase though when checking

**Pull request merged**
