### PR TITLE
Fix task name in error message for missing .api files (and add some hints)

### PR DESCRIPTION
**Pull request by joffrey-bion**
Resolves the task name bug mentioned in this issue: https://github.com/Kotlin/binary-compatibility-validator/issues/76

And also provides some hints about project renames (when a file is found with an incorrect name) and suggest deletion in case the rename is case-change-only.

I'm sorry if the diff is a bit chaotic, I tried to simplify some stuff in the implementation that accesses the files. Not sure why the objectfactory / filetrees were used there instead of plain listFiles().

### CODE REVIEW

**Review by qwwdfsad — COMMENTED** [review]
Build seems to fail, please fix corresponding tests

**Comment by joffrey-bion** [comment]
> Build seems to fail, please fix corresponding tests

Sorry about that, it seems I updated one work in the error message after running the tests. Will fix ASAP

**Comment by qwwdfsad** [comment]
Sorry, we've fixed it all separately and the changeset is no longer relevant.
All corresponding bugs are fixed though!

**Comment by joffrey-bion** [comment]
Sure, no worries. If the task name thing was fixed too, it's alright then :)

**Pull request closed without merging**
